Description: >
  Elastic Container Registry for helloworld.

Resources:
  ECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "helloworld"
      ImageScanningConfiguration:
          ScanOnPush: true

Outputs:
  Arn:
    Value: !GetAtt ECR.RepositoryUri
