# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
    build-packages:
        docker:
            - image: cimg/node:19.9.0
        working_directory: ~/helloworld_app
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - nodejs
            - run:
                  name: install dependencies
                  command: npm install
            - run:
                  name: build packages
                  command: npm run build
            - run:
                  name: run test
                  command: npm run test
            - save_cache:
                  keys:
                      - nodejs
    check-dockerfile-format:
        docker:
            # Use the same Docker base as the project
            - image: python:3.7.11-stretch

        working_directory: ~/helloworld_app
        steps:
            - checkout
            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "requirements.txt" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run:
                  name: install dependencies
                  command: |
                      python3 -m venv venv
                      . venv/bin/activate
                      make install
                      # Install hadolint
                      wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 &&\
                      chmod +x /bin/hadolint
            - save_cache:
                  paths:
                      - ./venv
                  key: v1-dependencies-{{ checksum "requirements.txt" }}

            # run lint!
            - run:
                  name: run lint
                  command: |
                      . venv/bin/activate
                      make lint
    create-scr:
        docker:
            - image: amazon/aws-cli
        steps:
            - checkout
            - run:
                  name: Ensure back-end infrastructure exists
                  command: |
                      aws cloudformation deploy \
                        --template-file .circleci/files/ecr.yml \
                        --tags project=helloworld_app \
                        --stack-name "helloworld_app"
