apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: helloworld
  region: us-east-1

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-0ed842fd0f191c3cc }
      us-east-1b: { id: subnet-04bda11b18a15028c }
      us-east-1c: { id: subnet-02bae1a83b42ee054 }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t2.micro
    desiredCapacity: 3
    privateNetworking: true
    minSize: 2
    maxSize: 4